notifications:
  email:
    recipients:
     - romeshselvan@hotmail.co.uk

    on_success: never
    on_failure: change

# safelist
branches:
  only:
  - master

language: java
sudo: required

 Build the Java app
jdk:
  - oraclejdk8

script:
- openssl aes-256-cbc -K "$ENCRYPT_K" -iv "$ENCRYPT_IV" -in "./codesign.asc.enc" -out "./codesign.asc" -d
- gpg --fast-import ./codesign.asc

after_success:
- mvn clean install
